# -*- coding: utf-8 -*-
"""python day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsYSwUCR4QodSgOSlBp5xCmZaLwdk86L

print("") = is used to print string in colsole or interface etc
"""

print("krrish")

"""here name and age are variables in which i stored strings
string = is always written in double inverted comma""
"""

name = "krrish"
age = "50"
print("his name is " + name + " to be honest")
print("he is " + age + " years old")

"""if i want to print variable age as here its not a string because its not inside "" so in print i will have to str(age) where it concerts integer age to str = string"""

name = "krrish"
age = 50
print("his name is " + name + " to be honest")
print("he is " + str(age) + " years old")

"""f string format helps to use variables easily instead od + name +, just use f"...{..}.."
"""

name = "krrish"
age = 50
print(f"his name is {name} to be honest")
print(f"he is {age} years old")

"""how to print index and know index of a string"""

name = "raj"
print(name[0])
print(name[1])
print(name[2])
print(name.index("r"))
print(name.index("a"))
print(name.index("j"))

"""how to make the whole string upper or lower case
also check is the strig upper case or lower case
to make the string upper and check it and similarly for lower
"""

name = "Raj"
print(name.isupper())
print(name.islower())
print(name.upper())
print(name.lower())
print(name.upper().isupper())
print(name.lower().islower())

"""to print lenth of the string how many words are there in the string
how to replace words in string
"""

name = "himesh is a cool bodyguard"
print(len(name))
print(name.replace("cool" , "bad"))

